"use client";

import { inter, suisseIntl } from "@/lib/home/fonts";

const SUMMARY = {
  callType: "Refill request",
  caller: "James Chen",
  phone: "(510) 555-0192",
  duration: "2m 15s",
  agent: "Refill Agent",
} as const;

const CAPTURED_POINTS = [
  "Verified patient DOB and active medication list",
  "Confirmed pharmacy on file — CVS #4821",
  "Routed to refill queue with 4:30 PM pickup ETA",
] as const;

const SYNC_TAGS = ["Chart note drafted", "SMS confirmation sent"] as const;

/** Post-call voice summary — inbox shader band (above Ambient). */
export function DoePhoneHomeVoiceCallSummaryVisual() {
  return (
    <div className={`home-voice-call-summary ${suisseIntl.className}`} aria-hidden>
      <div className="home-voice-call-summary__toolbar">
        <div className="home-voice-call-summary__toolbar-copy">
          <p className="home-voice-call-summary__eyebrow">Post-call summary</p>
          <p className="home-voice-call-summary__title">Generated by voice agent</p>
        </div>
        <span className={`home-voice-call-summary__status ${inter.className}`}>Synced</span>
      </div>

      <div className={`home-voice-call-summary__call-block ${inter.className}`}>
        <div className="home-voice-call-summary__call-head">
          <span className="home-voice-call-summary__call-type">{SUMMARY.callType}</span>
          <span className="home-voice-call-summary__call-duration">{SUMMARY.duration}</span>
        </div>
        <p className="home-voice-call-summary__caller">{SUMMARY.caller}</p>
        <p className="home-voice-call-summary__phone">{SUMMARY.phone}</p>
        <p className="home-voice-call-summary__agent">Handled by {SUMMARY.agent}</p>
      </div>

      <ul className="home-voice-call-summary__points">
        {CAPTURED_POINTS.map((point) => (
          <li key={point} className={`home-voice-call-summary__point ${inter.className}`}>
            <span className="home-voice-call-summary__point-mark" aria-hidden />
            <span className="home-voice-call-summary__point-text">{point}</span>
          </li>
        ))}
      </ul>

      <div className={`home-voice-call-summary__tags ${inter.className}`}>
        {SYNC_TAGS.map((tag) => (
          <span key={tag} className="home-voice-call-summary__tag">
            {tag}
          </span>
        ))}
      </div>
    </div>
  );
}
