import {
  STORY_FABRIC_TALL_LEFT_POSTER,
  STORY_FLOAT_MID_LEFT_POSTER,
  STORY_FLOAT_TOP_RIGHT_POSTER,
  STORY_GENOME_BOTTOM_RIGHT_POSTER,
  STORY_GENOME_TOP_LEFT_POSTER,
  STORY_GOALS_ARR_HERO_POSTER,
  STORY_MEET_DOE_POSTERS,
  STORY_PULSE_TALL_LEFT_POSTER,
  STORY_PULSE_WIDE_BOTTOM_POSTER,
  STORY_ROADMAP_FRONT_DESK_POSTER,
  STORY_ROADMAP_PRIOR_AUTH_POSTER,
  STORY_TEAM_JAMES_POSTER,
} from "@/lib/story/story-shader-posters";

/** Baked Doe grain shaders used as images on `/doehomepage`. */
export const DOEHOME_SHADERS = {
  hero: STORY_MEET_DOE_POSTERS[0],
  genome: STORY_GENOME_TOP_LEFT_POSTER,
  pulse: STORY_PULSE_WIDE_BOTTOM_POSTER,
  fabric: STORY_FABRIC_TALL_LEFT_POSTER,
  float: STORY_FLOAT_TOP_RIGHT_POSTER,
  chart: STORY_MEET_DOE_POSTERS[1],
  handoff: STORY_ROADMAP_FRONT_DESK_POSTER,
  connect: STORY_GENOME_BOTTOM_RIGHT_POSTER,
  open: STORY_MEET_DOE_POSTERS[2],
  book: STORY_PULSE_TALL_LEFT_POSTER,
  scribe: STORY_FLOAT_MID_LEFT_POSTER,
  auth: STORY_ROADMAP_PRIOR_AUTH_POSTER,
  board: STORY_TEAM_JAMES_POSTER,
  stack: STORY_MEET_DOE_POSTERS[3],
  cta: STORY_GOALS_ARR_HERO_POSTER,
} as const;

export const DOEHOME_SHADER_PRELOAD = [DOEHOME_SHADERS.hero, DOEHOME_SHADERS.genome] as const;
