import { DOE_HOME_HERO_DUSK_PALETTE } from "@/lib/proto/proto-shader-backdrop-colors";

/** Same dusk structure as hero — pushed saturation/chroma. */
export const MOTION_TEST_GRADIENT_PALETTE = {
  sand: "#FFE4A8",
  horizon: "#FF9428",
  clay: "#EE4428",
  mid: "#CC6838",
  umber: "#944828",
  deep: "#5C3018",
  back: DOE_HOME_HERO_DUSK_PALETTE.back,
} as const;

/** Text-local clip gradient — radial orange spotlight, red at edges/baseline. */
export const MOTION_TEST_GRADIENT_TEXT_PALETTE = {
  orange: "#FF9428",
  copper: "#FF9020",
  warm: "#FF8828",
  amber: "#F07838",
  clay: "#EE4428",
  red: "#E03830",
} as const;

export const MOTION_TEST_FPS = 30;
export const MOTION_TEST_WIDTH = 1920;
export const MOTION_TEST_HEIGHT = 1080;

/** Meet scale-down ends when Doe beat begins (~0.63s slow + fast shrink window). */
export const MOTION_TEST_FRONT_DESK_SLOW_END_FRAME =
  Math.round(0.5 * MOTION_TEST_FPS) + 4;
/** Fast shrink — a few frames (~230ms). */
export const MOTION_TEST_FRONT_DESK_FAST_FRAMES = 7;

export const MOTION_TEST_DOE_START_FRAME =
  MOTION_TEST_FRONT_DESK_SLOW_END_FRAME + MOTION_TEST_FRONT_DESK_FAST_FRAMES;

/** Brief pan up before scale. */
export const MOTION_TEST_DOE_PAN_FRAMES = 6;
export const MOTION_TEST_DOE_PAN_START_Y = 5.2;
export const MOTION_TEST_DOE_PAN_END_Y = 2;
/** Slow scale up on small Doe — trimmed by 1s (was full 1s hold on gradient). */
export const MOTION_TEST_DOE_SCALE_UP_FRAMES = 0;

export const MOTION_TEST_DOE_JUMP_FRAME =
  MOTION_TEST_DOE_START_FRAME +
  MOTION_TEST_DOE_PAN_FRAMES +
  MOTION_TEST_DOE_SCALE_UP_FRAMES;

/** Big Doe — solo center copy, then flash to stacked column. */
export const MOTION_TEST_DOE_STACK_FLASH_DELAY_FRAMES = 3;
export const MOTION_TEST_DOE_STACK_START_FRAME =
  MOTION_TEST_DOE_JUMP_FRAME + MOTION_TEST_DOE_STACK_FLASH_DELAY_FRAMES;

/** Hold full column on white, then invert to white stack on orange gradient. */
export const MOTION_TEST_DOE_STACK_HOLD_FRAMES = 18;
export const MOTION_TEST_DOE_STACK_INVERT_START_FRAME =
  MOTION_TEST_DOE_STACK_START_FRAME + MOTION_TEST_DOE_STACK_HOLD_FRAMES;
/** @deprecated Use MOTION_TEST_DOE_STACK_INVERT_START_FRAME */
export const MOTION_TEST_DOE_COLLAPSE_START_FRAME = MOTION_TEST_DOE_STACK_INVERT_START_FRAME;
export const MOTION_TEST_INVERT_GRADIENT_WHITE_OUT_FRAMES = 1;
/** @deprecated Use MOTION_TEST_INVERT_GRADIENT_WHITE_OUT_FRAMES */
export const MOTION_TEST_COLLAPSE_GRADIENT_WHITE_OUT_FRAMES = MOTION_TEST_INVERT_GRADIENT_WHITE_OUT_FRAMES;
/** Hold white stack on gradient before big white Doe flash. */
export const MOTION_TEST_STACK_WHITE_ON_GRADIENT_HOLD_FRAMES = 14;

export const MOTION_TEST_VERY_BIG_WHITE_FLASH_START_FRAME =
  MOTION_TEST_DOE_STACK_INVERT_START_FRAME + MOTION_TEST_STACK_WHITE_ON_GRADIENT_HOLD_FRAMES;
export const MOTION_TEST_STACK_HIDE_FRAME = MOTION_TEST_VERY_BIG_WHITE_FLASH_START_FRAME;
export const MOTION_TEST_VERY_BIG_WHITE_FLASH_HOLD_FRAMES = 20;

export const MOTION_TEST_OPPOSITE_COLOR_FLASH_START_FRAME =
  MOTION_TEST_VERY_BIG_WHITE_FLASH_START_FRAME + MOTION_TEST_VERY_BIG_WHITE_FLASH_HOLD_FRAMES;
export const MOTION_TEST_OPPOSITE_COLOR_FLASH_FRAMES = 1;
/** Flash settle + hold on clay Doe before finale typewriter. */
export const MOTION_TEST_OPPOSITE_COLOR_FLASH_HOLD_FRAMES = 8 + MOTION_TEST_FPS - 20;

/** @deprecated Use MOTION_TEST_OPPOSITE_COLOR_FLASH_START_FRAME */
export const MOTION_TEST_GRADIENT_DOE_START_FRAME = MOTION_TEST_OPPOSITE_COLOR_FLASH_START_FRAME;

export const MOTION_TEST_FINALE_TYPE_START_FRAME =
  MOTION_TEST_OPPOSITE_COLOR_FLASH_START_FRAME +
  MOTION_TEST_OPPOSITE_COLOR_FLASH_FRAMES +
  MOTION_TEST_OPPOSITE_COLOR_FLASH_HOLD_FRAMES;
export const MOTION_TEST_FINALE_BUILDING_WORD = "We're building";
export const MOTION_TEST_FINALE_BUILDING_LEADING_PREFIX = "We're ";
export const MOTION_TEST_FINALE_BUILDING_VISIBLE_SUFFIX = "building";
export const MOTION_TEST_FINALE_INTELLIGENCE_WORD = "intelligence";
export const MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_WORD = "intelligence for";
export const MOTION_TEST_FINALE_BUILDING_TYPE_FRAMES = 42;
export const MOTION_TEST_FINALE_BUILDING_HOLD_FRAMES = 0;
export const MOTION_TEST_FINALE_INTELLIGENCE_TYPE_FRAMES = 36;
export const MOTION_TEST_FINALE_INTELLIGENCE_HOLD_FRAMES = 0;
export const MOTION_TEST_FINALE_FULL_PHRASE_WORD = "We're building intelligence into";
export const MOTION_TEST_FINALE_SECOND_LINE_WORD = "every part of patient care.";
export const MOTION_TEST_FINALE_FULL_PHRASE_SCALE_DOWN_FRAMES = 40;
export const MOTION_TEST_FINALE_FULL_PHRASE_SCALE_HOLD_FRAMES = 0;
export const MOTION_TEST_FINALE_SECOND_LINE_PAN_FRAMES = 20;
export const MOTION_TEST_FINALE_SECOND_LINE_SCALE_CONTINUE_FRAMES = 30;
export const MOTION_TEST_FINALE_SECOND_LINE_HOLD_FRAMES = 4;
export const MOTION_TEST_FINALE_FULL_PHRASE_SCALE_START = 0.9;
export const MOTION_TEST_FINALE_FULL_PHRASE_SCALE_MID = 0.9;
export const MOTION_TEST_FINALE_FULL_PHRASE_SCALE_END = 0.78;

/** @deprecated Replaced by scale-down + two-line sequence */
export const MOTION_TEST_FINALE_FULL_PHRASE_HOLD_FRAMES = MOTION_TEST_FINALE_FULL_PHRASE_SCALE_HOLD_FRAMES;

function motionTestTypewriterGFrameOffset(typeFrames: number, letterCount: number): number {
  return Math.ceil(((letterCount - 1) * typeFrames) / letterCount);
}

/** First phrase-frame where a letter slot opens in the shared typewriter math. */
function motionTestTypewriterLetterStartFrame(
  typeFrames: number,
  text: string,
  letter: string,
): number {
  const letters = text.split("");
  const letterIndex = letters.indexOf(letter);
  if (letterIndex < 0) return typeFrames;

  const framesPerLetter = typeFrames / letters.length;
  return Math.floor(letterIndex * framesPerLetter);
}

/** First frame where the last letter (g) appears — cut to intelligence on the next frame. */
export const MOTION_TEST_FINALE_BUILDING_G_FRAME_OFFSET = motionTestTypewriterGFrameOffset(
  MOTION_TEST_FINALE_BUILDING_TYPE_FRAMES,
  MOTION_TEST_FINALE_BUILDING_WORD.length,
);

/** First frame where the last letter (e) appears — cut to full phrase on the next frame. */
export const MOTION_TEST_FINALE_INTELLIGENCE_E_FRAME_OFFSET = motionTestTypewriterGFrameOffset(
  MOTION_TEST_FINALE_INTELLIGENCE_TYPE_FRAMES,
  MOTION_TEST_FINALE_INTELLIGENCE_WORD.length,
);

/** @deprecated Use MOTION_TEST_FINALE_INTELLIGENCE_E_FRAME_OFFSET */
export const MOTION_TEST_FINALE_INTELLIGENCE_COMPLETE_OFFSET =
  MOTION_TEST_FINALE_INTELLIGENCE_E_FRAME_OFFSET;

/** @deprecated Use MOTION_TEST_FINALE_BUILDING_WORD */
export const MOTION_TEST_FINALE_TYPE_WORD = MOTION_TEST_FINALE_BUILDING_WORD;
/** @deprecated Use MOTION_TEST_FINALE_BUILDING_TYPE_FRAMES */
export const MOTION_TEST_FINALE_TYPE_FRAMES = MOTION_TEST_FINALE_BUILDING_TYPE_FRAMES;
/** @deprecated Use MOTION_TEST_FINALE_FULL_PHRASE_HOLD_FRAMES */
export const MOTION_TEST_FINALE_TYPE_HOLD_FRAMES = MOTION_TEST_FINALE_FULL_PHRASE_HOLD_FRAMES;

export const MOTION_TEST_FINALE_INTELLIGENCE_START_FRAME =
  MOTION_TEST_FINALE_TYPE_START_FRAME +
  MOTION_TEST_FINALE_BUILDING_G_FRAME_OFFSET +
  1 +
  MOTION_TEST_FINALE_BUILDING_HOLD_FRAMES;

export const MOTION_TEST_FINALE_FULL_PHRASE_START_FRAME =
  MOTION_TEST_FINALE_INTELLIGENCE_START_FRAME +
  MOTION_TEST_FINALE_INTELLIGENCE_E_FRAME_OFFSET +
  1 +
  MOTION_TEST_FINALE_INTELLIGENCE_HOLD_FRAMES;

export const MOTION_TEST_FINALE_INTELLIGENCE_BORDER_DRAW_FRAMES = 42;

const intelligenceIndex = MOTION_TEST_FINALE_FULL_PHRASE_WORD.indexOf(
  MOTION_TEST_FINALE_INTELLIGENCE_WORD,
);
export const MOTION_TEST_FINALE_FULL_PHRASE_BEFORE_INTELLIGENCE =
  intelligenceIndex >= 0
    ? MOTION_TEST_FINALE_FULL_PHRASE_WORD.slice(0, intelligenceIndex)
    : "";
export const MOTION_TEST_FINALE_FULL_PHRASE_AFTER_INTELLIGENCE =
  intelligenceIndex >= 0
    ? MOTION_TEST_FINALE_FULL_PHRASE_WORD.slice(
        intelligenceIndex + MOTION_TEST_FINALE_INTELLIGENCE_WORD.length,
      )
    : "";

/** Anchors second-line pan timing (same offset as former “t” in “ into”). */
export const MOTION_TEST_FINALE_INTO_TYPE_FRAMES = 15;

/** Phrase-frame offset — pan begins at the former “t” beat on the one-liner. */
export const MOTION_TEST_FINALE_TWO_LINE_PAN_START_OFFSET = motionTestTypewriterLetterStartFrame(
  MOTION_TEST_FINALE_INTO_TYPE_FRAMES,
  MOTION_TEST_FINALE_FULL_PHRASE_AFTER_INTELLIGENCE,
  "t",
);

export const MOTION_TEST_FINALE_TWO_LINE_PAN_START_FRAME =
  MOTION_TEST_FINALE_FULL_PHRASE_START_FRAME + MOTION_TEST_FINALE_TWO_LINE_PAN_START_OFFSET;

/** Mid-pan — snap to gradient bg + white text for “every part of patient care.” */
export const MOTION_TEST_FINALE_SECOND_LINE_COLOR_SWITCH_FRAME =
  MOTION_TEST_FINALE_TWO_LINE_PAN_START_FRAME +
  Math.floor(MOTION_TEST_FINALE_SECOND_LINE_PAN_FRAMES / 2);

export const MOTION_TEST_FINALE_TWO_LINE_SEQUENCE_END_FRAME =
  MOTION_TEST_FINALE_TWO_LINE_PAN_START_FRAME +
  MOTION_TEST_FINALE_SECOND_LINE_PAN_FRAMES +
  MOTION_TEST_FINALE_SECOND_LINE_SCALE_CONTINUE_FRAMES +
  MOTION_TEST_FINALE_SECOND_LINE_HOLD_FRAMES;

/** After two-line hold — cut to isolated “intelligence” on the next frame. */
export const MOTION_TEST_FINALE_INTELLIGENCE_ISOLATE_START_FRAME =
  MOTION_TEST_FINALE_TWO_LINE_SEQUENCE_END_FRAME;

/** Stack begins immediately — no solo intelligence hold. */
export const MOTION_TEST_FINALE_INTELLIGENCE_ISOLATE_HOLD_FRAMES = 0;
export const MOTION_TEST_FINALE_INTELLIGENCE_STACK_LINE_HEIGHT = 0.88;
export const MOTION_TEST_FINALE_INTELLIGENCE_STACK_OPACITY_FALLOFF = 0.17;
export const MOTION_TEST_FINALE_INTELLIGENCE_STACK_MIN_OPACITY = 0.06;
export const MOTION_TEST_FINALE_INTELLIGENCE_STACK_FRAMES = 18;
export const MOTION_TEST_FINALE_INTELLIGENCE_STACK_DRIFT_AMOUNT = 0.55;
export const MOTION_TEST_FINALE_INTELLIGENCE_STACK_PAN_UP_PX = 72;
/** Absolute timeline — circle + text scale-down begins at 10s. */
export const MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_ZOOM_START_SEC = 10;
export const MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_ZOOM_START_FRAME =
  Math.round(MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_ZOOM_START_SEC * MOTION_TEST_FPS);
/** Circle portal zoom-out — gradient + stack shrink together; white reveals on the right. */
export const MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_ZOOM_FRAMES = 20;
export const MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_HOLD_AFTER_ZOOM_FRAMES = 25;
/** Diameter fits frame height when scaled from full width. */
export const MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_ZOOM_END_SCALE =
  MOTION_TEST_HEIGHT / Math.max(MOTION_TEST_WIDTH, MOTION_TEST_HEIGHT);
/** Min text scale at zoom end — computed to fit phrase in circle; this is the floor. */
export const MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_TEXT_ZOOM_END_SCALE = 0.42;
/** Inset from circle right edge so “for” stays on gradient at zoom end. */
export const MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_TEXT_CIRCLE_INSET_PX = 56;
/** Approximate char width × letter-spacing for layout without measure. */
export const MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_TEXT_CHAR_WIDTH_RATIO = 0.46;

export const MOTION_TEST_FINALE_INTELLIGENCE_STACK_START_FRAME =
  MOTION_TEST_FINALE_INTELLIGENCE_ISOLATE_START_FRAME +
  MOTION_TEST_FINALE_INTELLIGENCE_ISOLATE_HOLD_FRAMES;

export const MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_START_FRAME =
  MOTION_TEST_FINALE_INTELLIGENCE_STACK_START_FRAME +
  MOTION_TEST_FINALE_INTELLIGENCE_STACK_FRAMES;

export const MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_HOLD_BEFORE_ZOOM_FRAMES =
  MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_ZOOM_START_FRAME -
  MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_START_FRAME;

/** Stack drift + pan run through hold and the first half of scale-down. */
export const MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_STACK_MOTION_FRAMES =
  MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_HOLD_BEFORE_ZOOM_FRAMES +
  Math.floor(MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_ZOOM_FRAMES / 2);

export const MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_HOLD_FRAMES =
  MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_HOLD_BEFORE_ZOOM_FRAMES +
  MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_ZOOM_FRAMES +
  MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_HOLD_AFTER_ZOOM_FRAMES;

export const MOTION_TEST_FINALE_END_FRAME =
  MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_ZOOM_START_FRAME +
  MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_ZOOM_FRAMES +
  MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_HOLD_AFTER_ZOOM_FRAMES;

/** @deprecated Use MOTION_TEST_FINALE_INTELLIGENCE_ISOLATE_HOLD_FRAMES */
export const MOTION_TEST_FINALE_INTELLIGENCE_BORDER_HOLD_FRAMES =
  MOTION_TEST_FINALE_INTELLIGENCE_ISOLATE_HOLD_FRAMES;

/** @deprecated Finale follows opposite-color flash directly */
export const MOTION_TEST_VERY_BIG_DOE_START_FRAME = MOTION_TEST_FINALE_TYPE_START_FRAME;

export const MOTION_TEST_TEXT_SEQUENCE_END_FRAME = MOTION_TEST_FINALE_END_FRAME;

/** Gradient pull completes as big Doe cuts in. */
export const MOTION_TEST_GRADIENT_PULL_FRAMES = MOTION_TEST_DOE_JUMP_FRAME;

export const MOTION_TEST_WHITE_HOLD_SEC = 1;
export const MOTION_TEST_WHITE_HOLD_FRAMES = MOTION_TEST_FPS * MOTION_TEST_WHITE_HOLD_SEC;

export const MOTION_TEST_TITLE_FRAMES = MOTION_TEST_FINALE_END_FRAME;
export const MOTION_TEST_DURATION_FRAMES = MOTION_TEST_TITLE_FRAMES;

/** Background bed — Jane & The Boy “Waste Our Time”. */
export const MOTION_TEST_BG_MUSIC_SRC = "motion/waste-our-time.mp3";
export const MOTION_TEST_BG_MUSIC_GAIN = 0.85;
export const MOTION_TEST_BG_MUSIC_START_SEC = 60 + 22;
export const MOTION_TEST_BG_MUSIC_START_FRAMES =
  MOTION_TEST_FPS * MOTION_TEST_BG_MUSIC_START_SEC;
export const MOTION_TEST_BG_MUSIC_END_FRAMES =
  MOTION_TEST_BG_MUSIC_START_FRAMES + MOTION_TEST_DURATION_FRAMES;
export const MOTION_TEST_BG_MUSIC_FADE_OUT_FRAMES = Math.round(2 * MOTION_TEST_FPS);

export const MOTION_TEST_PULL_FRAMES = MOTION_TEST_GRADIENT_PULL_FRAMES;
export const MOTION_TEST_PULL_SEC = MOTION_TEST_GRADIENT_PULL_FRAMES / MOTION_TEST_FPS;

/** Full-frame radial — same orange → red mix as clip-text, scaled for scene bg. */
export const MOTION_TEST_TITLE_GRADIENT = `radial-gradient(ellipse 140% 102% at 50% 0%, ${MOTION_TEST_GRADIENT_TEXT_PALETTE.orange} 0%, ${MOTION_TEST_GRADIENT_TEXT_PALETTE.copper} 10%, ${MOTION_TEST_GRADIENT_TEXT_PALETTE.warm} 22%, ${MOTION_TEST_GRADIENT_TEXT_PALETTE.amber} 36%, ${MOTION_TEST_GRADIENT_TEXT_PALETTE.clay} 52%, ${MOTION_TEST_GRADIENT_TEXT_PALETTE.red} 68%, ${MOTION_TEST_GRADIENT_PALETTE.back} 86%, ${MOTION_TEST_GRADIENT_PALETTE.back} 100%)`;

export const MOTION_TEST_GRADIENT_TEXT_GRADIENT = `radial-gradient(ellipse 130% 125% at 50% 12%, ${MOTION_TEST_GRADIENT_TEXT_PALETTE.orange} 0%, ${MOTION_TEST_GRADIENT_TEXT_PALETTE.copper} 16%, ${MOTION_TEST_GRADIENT_TEXT_PALETTE.warm} 32%, ${MOTION_TEST_GRADIENT_TEXT_PALETTE.amber} 48%, ${MOTION_TEST_GRADIENT_TEXT_PALETTE.clay} 66%, ${MOTION_TEST_GRADIENT_TEXT_PALETTE.red} 82%, ${MOTION_TEST_GRADIENT_TEXT_PALETTE.red} 100%)`;

export const MOTION_TEST_GRADIENT_LAYER_HEIGHT_RATIO = 2.75;
export const MOTION_TEST_PULL_START_Y_RATIO = -0.24;
export const MOTION_TEST_PULL_END_Y_RATIO = -0.05;

export const MOTION_TEST_WHITE_OVERLAY_FADE_FRAMES = 1;
export const MOTION_TEST_VERY_BIG_DOE_WHITE_IN_FRAMES = 2;

export const MOTION_TEST_TITLE_FONT_SIZE = 128;
export const MOTION_TEST_TEXT_SCALE_START = 1.08;
export const MOTION_TEST_TEXT_SCALE_END = 1;
export const MOTION_TEST_DOE_SCALE_DELTA =
  MOTION_TEST_TEXT_SCALE_START - MOTION_TEST_TEXT_SCALE_END;
export const MOTION_TEST_DOE_JUMP_FONT_SIZE = 156;
export const MOTION_TEST_DOE_JUMP_SCALE = 1.22;
export const MOTION_TEST_FRONT_DESK_FAST_SCALE_END = 0.88;

export const MOTION_TEST_DOE_STACK_RADIUS = 4;
export const MOTION_TEST_DOE_STACK_LINE_HEIGHT = 0.92;
export const MOTION_TEST_DOE_STACK_OPACITY_FALLOFF = 0.22;
export const MOTION_TEST_DOE_STACK_MIN_OPACITY = 0.07;

/** Very big white Doe flash — Lora on white. */
export const MOTION_TEST_VERY_BIG_DOE_FONT_SIZE = Math.round(MOTION_TEST_HEIGHT * 0.62);
export const MOTION_TEST_VERY_BIG_DOE_LINE_HEIGHT = 0.92;
export const MOTION_TEST_VERY_BIG_DOE_ON_WHITE_COLOR = MOTION_TEST_GRADIENT_PALETTE.clay;

/** Finale — DM Sans, solid clay red, very large. */
export const MOTION_TEST_FINALE_TYPE_COLOR = MOTION_TEST_GRADIENT_PALETTE.clay;
export const MOTION_TEST_FINALE_INVERTED_TEXT_COLOR = "#ffffff";
export const MOTION_TEST_FINALE_INTELLIGENCE_BORDER_COLOR = "rgba(0, 0, 0, 0.14)";
export const MOTION_TEST_FINALE_TYPE_FONT_SIZE = 340;
/** Scaled so full phrase fits dead center at 1920 — proportional to building beat width. */
export const MOTION_TEST_FINALE_FULL_PHRASE_FONT_SIZE = Math.round(
  (MOTION_TEST_FINALE_TYPE_FONT_SIZE * MOTION_TEST_FINALE_BUILDING_WORD.length) /
    MOTION_TEST_FINALE_FULL_PHRASE_WORD.length,
);
export const MOTION_TEST_FINALE_TYPE_LINE_HEIGHT = 0.94;
/** Tighter leading for the two-line full phrase stack. */
export const MOTION_TEST_FINALE_TWO_LINE_LEADING = 0.82;
export const MOTION_TEST_FINALE_CURSOR_BLINK_FRAMES = 16;
