import {
  DOE_LAUNCH_BROWN_BG,
  DOE_LAUNCH_GOLD_GRADIENT,
} from "@/remotion/constants";

/** Motion4 launch palette — gold + brown only. */
export const MOTION_TEST_GOLD_GRADIENT = DOE_LAUNCH_GOLD_GRADIENT;
export const MOTION_TEST_BROWN_BG_GRADIENT = DOE_LAUNCH_BROWN_BG;
export const MOTION_TEST_BROWN_TEXT_GRADIENT =
  "linear-gradient(180deg, #241c14 0%, #1a1208 52%, rgba(26, 18, 8, 0.72) 100%)";
export const MOTION_TEST_GOLD_LINE_STROKE_GRADIENT_HORIZONTAL =
  "linear-gradient(to right, #e8c08e 0%, #d4a574 52%, rgba(212, 165, 116, 0.72) 100%)";
export const MOTION_TEST_GOLD_LINE_STROKE_GRADIENT = MOTION_TEST_GOLD_GRADIENT;
export const MOTION_TEST_BROWN_LINE_STROKE_GRADIENT_HORIZONTAL =
  "linear-gradient(to right, #241c14 0%, #1a1208 52%, rgba(26, 18, 8, 0.72) 100%)";

export const MOTION_TEST_GOLD_MID = "#d4a574";
export const MOTION_TEST_GOLD_LIGHT = "#e8c08e";
export const MOTION_TEST_BROWN_MID = "#1a1208";
export const MOTION_TEST_BROWN_DEEP = "#241c14";

/** @deprecated Use MOTION_TEST_GOLD_MID / MOTION_TEST_BROWN_MID — kept for solid-accent call sites. */
export const MOTION_TEST_GRADIENT_PALETTE = {
  sand: MOTION_TEST_GOLD_MID,
  horizon: MOTION_TEST_GOLD_MID,
  clay: MOTION_TEST_BROWN_MID,
  mid: MOTION_TEST_GOLD_MID,
  umber: MOTION_TEST_BROWN_MID,
  deep: MOTION_TEST_BROWN_MID,
  back: MOTION_TEST_BROWN_MID,
} as const;

/** Brown gradient text stops — same 180deg direction as motion4 gold. */
export const MOTION_TEST_GRADIENT_TEXT_PALETTE = {
  orange: MOTION_TEST_BROWN_MID,
  copper: MOTION_TEST_BROWN_MID,
  warm: MOTION_TEST_BROWN_MID,
  amber: MOTION_TEST_BROWN_MID,
  clay: MOTION_TEST_BROWN_MID,
  red: MOTION_TEST_BROWN_MID,
} as const;

export const MOTION_TEST_FPS = 60;
/** Motion timing is authored at 30fps — convert output frames with getMotionTestDesignFrame. */
export const MOTION_TEST_DESIGN_FPS = 30;
/** Master composition length — all finale timing derives to hit this exactly. */
export const MOTION_TEST_DURATION_SEC = 40.5;
export const MOTION_TEST_WIDTH = 3840;
export const MOTION_TEST_HEIGHT = 2160;
/** Layout tokens below were authored at 1080p — scale fixed px/font sizes for output resolution. */
export const MOTION_TEST_DESIGN_HEIGHT = 1080;
export const MOTION_TEST_RES_SCALE = MOTION_TEST_HEIGHT / MOTION_TEST_DESIGN_HEIGHT;

export function motionTestPx(value: number): number {
  return Math.round(value * MOTION_TEST_RES_SCALE);
}

/** Meet scale-down ends when Doe beat begins (~0.63s slow + fast shrink window). */
export const MOTION_TEST_FRONT_DESK_SLOW_END_FRAME =
  Math.round(0.5 * MOTION_TEST_DESIGN_FPS) + 4;
/** Fast shrink — a few frames (~230ms). */
export const MOTION_TEST_FRONT_DESK_FAST_FRAMES = 7;

export const MOTION_TEST_DOE_START_FRAME =
  MOTION_TEST_FRONT_DESK_SLOW_END_FRAME + MOTION_TEST_FRONT_DESK_FAST_FRAMES;

/** Brief pan up before scale. */
export const MOTION_TEST_DOE_PAN_FRAMES = 6;
export const MOTION_TEST_DOE_PAN_START_Y = 5.2;
export const MOTION_TEST_DOE_PAN_END_Y = 2;
/** Slow scale up on small Doe — trimmed by 1s (was full 1s hold on gradient). */
export const MOTION_TEST_DOE_SCALE_UP_FRAMES = 0;

export const MOTION_TEST_DOE_JUMP_FRAME =
  MOTION_TEST_DOE_START_FRAME +
  MOTION_TEST_DOE_PAN_FRAMES +
  MOTION_TEST_DOE_SCALE_UP_FRAMES;

/** Big Doe — solo center copy, then flash to stacked column. */
export const MOTION_TEST_DOE_STACK_FLASH_DELAY_FRAMES = 3;
export const MOTION_TEST_DOE_STACK_START_FRAME =
  MOTION_TEST_DOE_JUMP_FRAME + MOTION_TEST_DOE_STACK_FLASH_DELAY_FRAMES;

/** Hold full column on white, then invert to white stack on orange gradient. */
export const MOTION_TEST_DOE_STACK_HOLD_FRAMES = 18;
export const MOTION_TEST_DOE_STACK_INVERT_START_FRAME =
  MOTION_TEST_DOE_STACK_START_FRAME + MOTION_TEST_DOE_STACK_HOLD_FRAMES;
/** One frame — opening peach-orange gradient clipped inside stack text at invert. */
export const MOTION_TEST_DOE_STACK_OPENING_GRADIENT_TEXT_FRAME =
  MOTION_TEST_DOE_STACK_INVERT_START_FRAME;
/** Reversed stack hold — dark brown bed behind white Doe column. */
export const MOTION_TEST_DOE_STACK_REVERSED_BACKGROUND_START_FRAME =
  MOTION_TEST_DOE_STACK_INVERT_START_FRAME + 1;
/** @deprecated Use MOTION_TEST_DOE_STACK_INVERT_START_FRAME */
export const MOTION_TEST_DOE_COLLAPSE_START_FRAME = MOTION_TEST_DOE_STACK_INVERT_START_FRAME;
export const MOTION_TEST_INVERT_GRADIENT_WHITE_OUT_FRAMES = 1;
/** @deprecated Use MOTION_TEST_INVERT_GRADIENT_WHITE_OUT_FRAMES */
export const MOTION_TEST_COLLAPSE_GRADIENT_WHITE_OUT_FRAMES = MOTION_TEST_INVERT_GRADIENT_WHITE_OUT_FRAMES;
/** Hold white stack on gradient before big white Doe flash. */
export const MOTION_TEST_STACK_WHITE_ON_GRADIENT_HOLD_FRAMES = 14;

export const MOTION_TEST_VERY_BIG_WHITE_FLASH_START_FRAME =
  MOTION_TEST_DOE_STACK_INVERT_START_FRAME + MOTION_TEST_STACK_WHITE_ON_GRADIENT_HOLD_FRAMES;
export const MOTION_TEST_STACK_HIDE_FRAME = MOTION_TEST_VERY_BIG_WHITE_FLASH_START_FRAME;
export const MOTION_TEST_VERY_BIG_WHITE_FLASH_HOLD_FRAMES = 20;

export const MOTION_TEST_OPPOSITE_COLOR_FLASH_START_FRAME =
  MOTION_TEST_VERY_BIG_WHITE_FLASH_START_FRAME + MOTION_TEST_VERY_BIG_WHITE_FLASH_HOLD_FRAMES;
export const MOTION_TEST_OPPOSITE_COLOR_FLASH_FRAMES = 1;
/** Flash settle + hold on clay Doe before finale typewriter. */
export const MOTION_TEST_OPPOSITE_COLOR_FLASH_HOLD_FRAMES = 8 + MOTION_TEST_DESIGN_FPS - 20;

/** @deprecated Use MOTION_TEST_OPPOSITE_COLOR_FLASH_START_FRAME */
export const MOTION_TEST_GRADIENT_DOE_START_FRAME = MOTION_TEST_OPPOSITE_COLOR_FLASH_START_FRAME;

export const MOTION_TEST_FINALE_TYPE_START_FRAME =
  MOTION_TEST_OPPOSITE_COLOR_FLASH_START_FRAME +
  MOTION_TEST_OPPOSITE_COLOR_FLASH_FRAMES +
  MOTION_TEST_OPPOSITE_COLOR_FLASH_HOLD_FRAMES;
export const MOTION_TEST_FINALE_BUILDING_WORD = "We're building";
export const MOTION_TEST_FINALE_BUILDING_LEADING_PREFIX = "We're ";
export const MOTION_TEST_FINALE_BUILDING_VISIBLE_SUFFIX = "building";
export const MOTION_TEST_FINALE_INTELLIGENCE_WORD = "intelligence";
export const MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_WORD = "intelligence for";
export const MOTION_TEST_FINALE_INTELLIGENCE_RESOLVE_SUFFIX = " built by";
export const MOTION_TEST_FINALE_INTELLIGENCE_RESOLVE_PHRASE = "intelligence built by";
export const MOTION_TEST_FINALE_RESOLVE_LINE1_WORDS = [
  MOTION_TEST_FINALE_INTELLIGENCE_WORD,
  "built",
  "by",
] as const;
export const MOTION_TEST_FINALE_RESOLVE_SEGMENT_FRAMES = 5;
export const MOTION_TEST_FINALE_RESOLVE_LINE2_TAIL_WORDS = ["at", "every", "stage"] as const;
export const MOTION_TEST_FINALE_RESOLVE_LINE2_START_FRAME =
  MOTION_TEST_FINALE_RESOLVE_LINE1_WORDS.length *
  MOTION_TEST_FINALE_RESOLVE_SEGMENT_FRAMES;
export const MOTION_TEST_FINALE_BUILDING_TYPE_FRAMES = 42;
export const MOTION_TEST_FINALE_BUILDING_HOLD_FRAMES = 0;
export const MOTION_TEST_FINALE_INTELLIGENCE_TYPE_FRAMES = 36;
export const MOTION_TEST_FINALE_INTELLIGENCE_HOLD_FRAMES = 0;
export const MOTION_TEST_FINALE_FULL_PHRASE_WORD = "We're building intelligence into";
export const MOTION_TEST_FINALE_SECOND_LINE_WORD = "every part of patient care.";
export const MOTION_TEST_FINALE_FULL_PHRASE_SCALE_DOWN_FRAMES = 40;
export const MOTION_TEST_FINALE_FULL_PHRASE_SCALE_HOLD_FRAMES = 0;
export const MOTION_TEST_FINALE_SECOND_LINE_PAN_FRAMES = 20;
export const MOTION_TEST_FINALE_SECOND_LINE_SCALE_CONTINUE_FRAMES = 30;
export const MOTION_TEST_FINALE_SECOND_LINE_HOLD_FRAMES = 4;
export const MOTION_TEST_FINALE_FULL_PHRASE_SCALE_START = 0.9;
export const MOTION_TEST_FINALE_FULL_PHRASE_SCALE_MID = 0.9;
export const MOTION_TEST_FINALE_FULL_PHRASE_SCALE_END = 0.78;

/** @deprecated Replaced by scale-down + two-line sequence */
export const MOTION_TEST_FINALE_FULL_PHRASE_HOLD_FRAMES = MOTION_TEST_FINALE_FULL_PHRASE_SCALE_HOLD_FRAMES;

function motionTestTypewriterGFrameOffset(typeFrames: number, letterCount: number): number {
  return Math.ceil(((letterCount - 1) * typeFrames) / letterCount);
}

/** First phrase-frame where a letter slot opens in the shared typewriter math. */
function motionTestTypewriterLetterStartFrame(
  typeFrames: number,
  text: string,
  letter: string,
): number {
  const letters = text.split("");
  const letterIndex = letters.indexOf(letter);
  if (letterIndex < 0) return typeFrames;

  const framesPerLetter = typeFrames / letters.length;
  return Math.floor(letterIndex * framesPerLetter);
}

/** First frame where the last letter (g) appears — cut to intelligence on the next frame. */
export const MOTION_TEST_FINALE_BUILDING_G_FRAME_OFFSET = motionTestTypewriterGFrameOffset(
  MOTION_TEST_FINALE_BUILDING_TYPE_FRAMES,
  MOTION_TEST_FINALE_BUILDING_WORD.length,
);

/** First frame where the last letter (e) appears — cut to full phrase on the next frame. */
export const MOTION_TEST_FINALE_INTELLIGENCE_E_FRAME_OFFSET = motionTestTypewriterGFrameOffset(
  MOTION_TEST_FINALE_INTELLIGENCE_TYPE_FRAMES,
  MOTION_TEST_FINALE_INTELLIGENCE_WORD.length,
);

/** @deprecated Use MOTION_TEST_FINALE_INTELLIGENCE_E_FRAME_OFFSET */
export const MOTION_TEST_FINALE_INTELLIGENCE_COMPLETE_OFFSET =
  MOTION_TEST_FINALE_INTELLIGENCE_E_FRAME_OFFSET;

/** @deprecated Use MOTION_TEST_FINALE_BUILDING_WORD */
export const MOTION_TEST_FINALE_TYPE_WORD = MOTION_TEST_FINALE_BUILDING_WORD;
/** @deprecated Use MOTION_TEST_FINALE_BUILDING_TYPE_FRAMES */
export const MOTION_TEST_FINALE_TYPE_FRAMES = MOTION_TEST_FINALE_BUILDING_TYPE_FRAMES;
/** @deprecated Use MOTION_TEST_FINALE_FULL_PHRASE_HOLD_FRAMES */
export const MOTION_TEST_FINALE_TYPE_HOLD_FRAMES = MOTION_TEST_FINALE_FULL_PHRASE_HOLD_FRAMES;

export const MOTION_TEST_FINALE_INTELLIGENCE_START_FRAME =
  MOTION_TEST_FINALE_TYPE_START_FRAME +
  MOTION_TEST_FINALE_BUILDING_G_FRAME_OFFSET +
  1 +
  MOTION_TEST_FINALE_BUILDING_HOLD_FRAMES;

export const MOTION_TEST_FINALE_FULL_PHRASE_START_FRAME =
  MOTION_TEST_FINALE_INTELLIGENCE_START_FRAME +
  MOTION_TEST_FINALE_INTELLIGENCE_E_FRAME_OFFSET +
  1 +
  MOTION_TEST_FINALE_INTELLIGENCE_HOLD_FRAMES;

export const MOTION_TEST_FINALE_INTELLIGENCE_BORDER_DRAW_FRAMES = 42;

const intelligenceIndex = MOTION_TEST_FINALE_FULL_PHRASE_WORD.indexOf(
  MOTION_TEST_FINALE_INTELLIGENCE_WORD,
);
export const MOTION_TEST_FINALE_FULL_PHRASE_BEFORE_INTELLIGENCE =
  intelligenceIndex >= 0
    ? MOTION_TEST_FINALE_FULL_PHRASE_WORD.slice(0, intelligenceIndex)
    : "";
export const MOTION_TEST_FINALE_FULL_PHRASE_AFTER_INTELLIGENCE =
  intelligenceIndex >= 0
    ? MOTION_TEST_FINALE_FULL_PHRASE_WORD.slice(
        intelligenceIndex + MOTION_TEST_FINALE_INTELLIGENCE_WORD.length,
      )
    : "";

/** Anchors second-line pan timing (same offset as former “t” in “ into”). */
export const MOTION_TEST_FINALE_INTO_TYPE_FRAMES = 15;

/** Phrase-frame offset — pan begins at the former “t” beat on the one-liner. */
export const MOTION_TEST_FINALE_TWO_LINE_PAN_START_OFFSET = motionTestTypewriterLetterStartFrame(
  MOTION_TEST_FINALE_INTO_TYPE_FRAMES,
  MOTION_TEST_FINALE_FULL_PHRASE_AFTER_INTELLIGENCE,
  "t",
);

export const MOTION_TEST_FINALE_TWO_LINE_PAN_START_FRAME =
  MOTION_TEST_FINALE_FULL_PHRASE_START_FRAME + MOTION_TEST_FINALE_TWO_LINE_PAN_START_OFFSET;

/** Mid-pan — snap to gradient bg + white text for “every part of patient care.” */
export const MOTION_TEST_FINALE_SECOND_LINE_COLOR_SWITCH_FRAME =
  MOTION_TEST_FINALE_TWO_LINE_PAN_START_FRAME +
  Math.floor(MOTION_TEST_FINALE_SECOND_LINE_PAN_FRAMES / 2);

export const MOTION_TEST_FINALE_TWO_LINE_SEQUENCE_END_FRAME =
  MOTION_TEST_FINALE_TWO_LINE_PAN_START_FRAME +
  MOTION_TEST_FINALE_SECOND_LINE_PAN_FRAMES +
  MOTION_TEST_FINALE_SECOND_LINE_SCALE_CONTINUE_FRAMES +
  MOTION_TEST_FINALE_SECOND_LINE_HOLD_FRAMES;

/** After two-line hold — cut to isolated “intelligence” on the next frame. */
export const MOTION_TEST_FINALE_INTELLIGENCE_ISOLATE_START_FRAME =
  MOTION_TEST_FINALE_TWO_LINE_SEQUENCE_END_FRAME;

/** Stack begins immediately — no solo intelligence hold. */
export const MOTION_TEST_FINALE_INTELLIGENCE_ISOLATE_HOLD_FRAMES = 0;
export const MOTION_TEST_FINALE_INTELLIGENCE_STACK_LINE_HEIGHT = 0.88;
export const MOTION_TEST_FINALE_INTELLIGENCE_STACK_OPACITY_FALLOFF = 0.17;
export const MOTION_TEST_FINALE_INTELLIGENCE_STACK_MIN_OPACITY = 0.06;
export const MOTION_TEST_FINALE_INTELLIGENCE_STACK_FRAMES = 18;
export const MOTION_TEST_FINALE_INTELLIGENCE_STACK_DRIFT_AMOUNT = 0.55;
export const MOTION_TEST_FINALE_INTELLIGENCE_STACK_PAN_UP_PX = motionTestPx(72);
/** Absolute timeline — circle + text scale-down begins at 10s. */
export const MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_ZOOM_START_SEC = 10;
export const MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_ZOOM_START_FRAME =
  Math.round(MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_ZOOM_START_SEC * MOTION_TEST_DESIGN_FPS);
/** Circle portal zoom-out — gradient + stack shrink together; white reveals on the right. */
export const MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_ZOOM_FRAMES = 20;
/** Absolute timeline — audience carousel begins as the white panel opens (~mid zoom). */
export const MOTION_TEST_FINALE_AUDIENCE_CAROUSEL_START_SEC = 10.4;
export const MOTION_TEST_FINALE_AUDIENCE_CAROUSEL_START_FRAME =
  Math.round(MOTION_TEST_FINALE_AUDIENCE_CAROUSEL_START_SEC * MOTION_TEST_DESIGN_FPS);
export const MOTION_TEST_FINALE_AUDIENCE_CAROUSEL_ITEMS = [
  "doctors",
  "clinics",
  "hospitals",
  "patients",
  "insurers",
  "trainees",
] as const;
/** Second resolve row — audience word, then “at every stage” appended in place. */
export const MOTION_TEST_FINALE_RESOLVE_LINE2_WORDS = [
  MOTION_TEST_FINALE_AUDIENCE_CAROUSEL_ITEMS[0],
  ...MOTION_TEST_FINALE_RESOLVE_LINE2_TAIL_WORDS,
] as const;
export const MOTION_TEST_FINALE_RESOLVE_TOTAL_STEPS =
  MOTION_TEST_FINALE_RESOLVE_LINE1_WORDS.length +
  MOTION_TEST_FINALE_RESOLVE_LINE2_WORDS.length;
export const MOTION_TEST_FINALE_RESOLVE_SEQUENCE_FRAMES =
  MOTION_TEST_FINALE_RESOLVE_TOTAL_STEPS *
  MOTION_TEST_FINALE_RESOLVE_SEGMENT_FRAMES;
export const MOTION_TEST_FINALE_RESOLVE_HOLD_FRAMES = 18;
/** @deprecated Line 3 is the discipline carousel — see MOTION_TEST_FINALE_DISCIPLINE_CAROUSEL_ITEMS */
export const MOTION_TEST_FINALE_RESOLVE_LINE3_WORD = "product design";
export type MotionTestFinaleDisciplineCarouselIcon =
  | "design"
  | "engineering"
  | "distribution"
  | "growth";
export type MotionTestFinaleDisciplineCarouselItem = {
  label: string;
  icon: MotionTestFinaleDisciplineCarouselIcon;
};
export const MOTION_TEST_FINALE_DISCIPLINE_CAROUSEL_ITEMS = [
  { label: "product design", icon: "design" },
  { label: "engineering", icon: "engineering" },
  { label: "distribution", icon: "distribution" },
  { label: "growth", icon: "growth" },
] as const satisfies readonly MotionTestFinaleDisciplineCarouselItem[];
/** Nudge line-3 carousel right vs lines 1–2 anchor. */
export const MOTION_TEST_FINALE_DISCIPLINE_CAROUSEL_OFFSET_X_EM = 0;
export const MOTION_TEST_FINALE_DISCIPLINE_CAROUSEL_HOLD_FRAMES = 22;
export const MOTION_TEST_FINALE_DISCIPLINE_CAROUSEL_TRANSITION_FRAMES = 10;
export const MOTION_TEST_FINALE_DISCIPLINE_CAROUSEL_SLOT_FRAMES =
  MOTION_TEST_FINALE_DISCIPLINE_CAROUSEL_HOLD_FRAMES +
  MOTION_TEST_FINALE_DISCIPLINE_CAROUSEL_TRANSITION_FRAMES;
export const MOTION_TEST_FINALE_RESOLVE_THREE_LINE_PAN_FRAMES =
  MOTION_TEST_FINALE_SECOND_LINE_PAN_FRAMES;
/** Hold on switched colours (white text / gradient bg) through end card. */
export const MOTION_TEST_FINALE_RESOLVE_SWITCHED_HOLD_FRAMES = 18;
export const MOTION_TEST_FINALE_RESOLVE_THREE_LINE_HOLD_FRAMES =
  MOTION_TEST_FINALE_RESOLVE_SWITCHED_HOLD_FRAMES;
export const MOTION_TEST_FINALE_DISCIPLINE_CAROUSEL_INTRO_FRAMES =
  MOTION_TEST_FINALE_RESOLVE_THREE_LINE_PAN_FRAMES +
  MOTION_TEST_FINALE_RESOLVE_HOLD_FRAMES;
export const MOTION_TEST_FINALE_DISCIPLINE_CAROUSEL_FRAMES =
  MOTION_TEST_FINALE_DISCIPLINE_CAROUSEL_INTRO_FRAMES +
  (MOTION_TEST_FINALE_DISCIPLINE_CAROUSEL_ITEMS.length - 1) *
    MOTION_TEST_FINALE_DISCIPLINE_CAROUSEL_SLOT_FRAMES;
/** @deprecated Use MOTION_TEST_FINALE_RESOLVE_LINE2_WORDS[0] */
export const MOTION_TEST_FINALE_RESOLVE_LINE2_WORD =
  MOTION_TEST_FINALE_RESOLVE_LINE2_WORDS[0];
/** Third visible “intelligence for” line in the five-line stack (−2, −1, 0, 1, 2). */
export const MOTION_TEST_FINALE_AUDIENCE_CAROUSEL_STACK_ALIGN_OFFSET = 0;
/** Gap between portal edge and carousel text in the white panel. */
export const MOTION_TEST_FINALE_AUDIENCE_CAROUSEL_WHITE_GAP_PX = motionTestPx(36);
export const MOTION_TEST_FINALE_AUDIENCE_CAROUSEL_WORD_HOLD_FRAMES = 22;
export const MOTION_TEST_FINALE_AUDIENCE_CAROUSEL_WORD_TRANSITION_FRAMES = 8;
export const MOTION_TEST_FINALE_AUDIENCE_CAROUSEL_WORD_FRAMES =
  MOTION_TEST_FINALE_AUDIENCE_CAROUSEL_WORD_HOLD_FRAMES +
  MOTION_TEST_FINALE_AUDIENCE_CAROUSEL_WORD_TRANSITION_FRAMES;
export const MOTION_TEST_FINALE_AUDIENCE_CAROUSEL_FRAMES =
  MOTION_TEST_FINALE_AUDIENCE_CAROUSEL_ITEMS.length *
  MOTION_TEST_FINALE_AUDIENCE_CAROUSEL_WORD_FRAMES;
export const MOTION_TEST_FINALE_TRAINEES_CAROUSEL_INDEX =
  MOTION_TEST_FINALE_AUDIENCE_CAROUSEL_ITEMS.length - 1;
/** Brief beat on “trainees” before built-by resolve — not the full word slot. */
export const MOTION_TEST_FINALE_TRAINEES_HOLD_BEFORE_RESOLVE_FRAMES = 8;
/** Right after “trainees” lands — swap suffix + fill gradient. */
export const MOTION_TEST_FINALE_GRADIENT_RESOLVE_START_FRAME =
  MOTION_TEST_FINALE_AUDIENCE_CAROUSEL_START_FRAME +
  MOTION_TEST_FINALE_TRAINEES_CAROUSEL_INDEX *
    MOTION_TEST_FINALE_AUDIENCE_CAROUSEL_WORD_FRAMES +
  MOTION_TEST_FINALE_TRAINEES_HOLD_BEFORE_RESOLVE_FRAMES;
export const MOTION_TEST_FINALE_RESOLVE_THREE_LINE_PAN_START_FRAME =
  MOTION_TEST_FINALE_GRADIENT_RESOLVE_START_FRAME +
  MOTION_TEST_FINALE_RESOLVE_SEQUENCE_FRAMES +
  MOTION_TEST_FINALE_RESOLVE_HOLD_FRAMES;
/** Mid line-3 pan — gradient text on white → white text on gradient; locked through end card. */
export const MOTION_TEST_FINALE_RESOLVE_LINE3_COLOR_SWITCH_FRAME =
  MOTION_TEST_FINALE_RESOLVE_THREE_LINE_PAN_START_FRAME +
  Math.floor(MOTION_TEST_FINALE_RESOLVE_THREE_LINE_PAN_FRAMES / 2);
export const MOTION_TEST_FINALE_RESOLVE_THREE_LINE_END_FRAME =
  MOTION_TEST_FINALE_RESOLVE_THREE_LINE_PAN_START_FRAME +
  MOTION_TEST_FINALE_DISCIPLINE_CAROUSEL_FRAMES;
/** Growth lands — same frame the three-line stack is fully readable top → bottom. */
export const MOTION_TEST_FINALE_DISCIPLINE_GROWTH_START_FRAME =
  MOTION_TEST_FINALE_RESOLVE_THREE_LINE_END_FRAME;
export const MOTION_TEST_FINALE_VERTICAL_LINE_WIDTH_PX = motionTestPx(3);
/** Typewriter beat — bottom horizontal only; thicker + faster sweep than corner rig. */
export const MOTION_TEST_FINALE_TYPEWRITER_BOTTOM_LINE_WIDTH_PX = motionTestPx(18);
/** Already on screen from the left when the first "W" frame lands. */
export const MOTION_TEST_FINALE_TYPEWRITER_BOTTOM_LINE_INITIAL_VISIBLE_FRACTION = 1 / 12;
/** Pre-roll before typing — line is already sliding when the beat becomes visible. */
export const MOTION_TEST_FINALE_TYPEWRITER_BOTTOM_LINE_PRE_ROLL_FRAMES = 12;
/** Same frame as the building typewriter cut — first letter "W". */
export const MOTION_TEST_FINALE_TYPEWRITER_BOTTOM_LINE_START_FRAME =
  MOTION_TEST_FINALE_TYPE_START_FRAME;
/** Motion clock starts early so the sweep has velocity at the first typing frame. */
export const MOTION_TEST_FINALE_TYPEWRITER_BOTTOM_LINE_ANIMATION_START_FRAME =
  MOTION_TEST_FINALE_TYPEWRITER_BOTTOM_LINE_START_FRAME -
  MOTION_TEST_FINALE_TYPEWRITER_BOTTOM_LINE_PRE_ROLL_FRAMES;
/** Sweeps through intelligence typing — right edge lands on last intelligence frame. */
export const MOTION_TEST_FINALE_TYPEWRITER_BOTTOM_LINE_DRAW_FRAMES =
  MOTION_TEST_FINALE_FULL_PHRASE_START_FRAME -
  MOTION_TEST_FINALE_TYPEWRITER_BOTTOM_LINE_START_FRAME;
/** Shared inset from right (vertical) and bottom (horizontal). */
export const MOTION_TEST_FINALE_CORNER_LINE_EDGE_INSET_PX =
  MOTION_TEST_WIDTH / 4 - motionTestPx(192);
/** @deprecated Use MOTION_TEST_FINALE_CORNER_LINE_EDGE_INSET_PX */
export const MOTION_TEST_FINALE_VERTICAL_LINE_RIGHT_INSET_PX =
  MOTION_TEST_FINALE_CORNER_LINE_EDGE_INSET_PX;
export const MOTION_TEST_FINALE_CORNER_LINE_BOTTOM_INSET_PX =
  MOTION_TEST_FINALE_CORNER_LINE_EDGE_INSET_PX;
export const MOTION_TEST_FINALE_CORNER_LINE_TOP_INSET_PX =
  MOTION_TEST_FINALE_CORNER_LINE_EDGE_INSET_PX;
/** @deprecated Corner lines now span to the shared inset. */
export const MOTION_TEST_FINALE_VERTICAL_LINE_HEIGHT_RATIO = 0.75;
export const MOTION_TEST_FINALE_VERTICAL_LINE_DROP_FRAMES = 42;
/** When primary horizontal + vertical cross at the inset corner. */
export const MOTION_TEST_FINALE_CORNER_LINE_INTERSECT_PROGRESS = Math.max(
  (MOTION_TEST_WIDTH - MOTION_TEST_FINALE_CORNER_LINE_EDGE_INSET_PX) / MOTION_TEST_WIDTH,
  (MOTION_TEST_HEIGHT - MOTION_TEST_FINALE_CORNER_LINE_BOTTOM_INSET_PX) /
    MOTION_TEST_HEIGHT,
);
export const MOTION_TEST_FINALE_CORNER_LINE_INTERSECT_FRAME_OFFSET = Math.round(
  MOTION_TEST_FINALE_CORNER_LINE_INTERSECT_PROGRESS *
    MOTION_TEST_FINALE_VERTICAL_LINE_DROP_FRAMES,
);
export const MOTION_TEST_FINALE_CORNER_LINE_PHASE2_FRAMES =
  MOTION_TEST_FINALE_VERTICAL_LINE_DROP_FRAMES;
export const MOTION_TEST_FINALE_CORNER_LINE_TOTAL_FRAMES =
  MOTION_TEST_FINALE_CORNER_LINE_INTERSECT_FRAME_OFFSET +
  MOTION_TEST_FINALE_CORNER_LINE_PHASE2_FRAMES;
/** @deprecated Use MOTION_TEST_FINALE_VERTICAL_LINE_DROP_FRAMES */
export const MOTION_TEST_FINALE_VERTICAL_LINE_SWEEP_FRAMES =
  MOTION_TEST_FINALE_VERTICAL_LINE_DROP_FRAMES;
export const MOTION_TEST_FINALE_VERTICAL_LINE_START_FRAME =
  MOTION_TEST_FINALE_DISCIPLINE_GROWTH_START_FRAME;
export const MOTION_TEST_FINALE_VERTICAL_LINE_END_FRAME =
  MOTION_TEST_FINALE_VERTICAL_LINE_START_FRAME +
  MOTION_TEST_FINALE_CORNER_LINE_TOTAL_FRAMES;
export const MOTION_TEST_FINALE_PRODUCT_TITLES = [
  "Agent Builder",
  "Voice Agents",
  "Smart Appointments",
  "Auto Prior Auth",
] as const;
/** @deprecated Use MOTION_TEST_FINALE_PRODUCT_TITLES[0] */
export const MOTION_TEST_FINALE_AGENT_BUILDER_TITLE = MOTION_TEST_FINALE_PRODUCT_TITLES[0];
/** Mirror corner lines + product titles + resolve swipe — phase 2 start. */
export const MOTION_TEST_FINALE_CORNER_LINE_PHASE2_START_FRAME =
  MOTION_TEST_FINALE_VERTICAL_LINE_START_FRAME +
  MOTION_TEST_FINALE_CORNER_LINE_INTERSECT_FRAME_OFFSET;
export const MOTION_TEST_FINALE_AGENT_BUILDER_START_FRAME =
  MOTION_TEST_FINALE_CORNER_LINE_PHASE2_START_FRAME;
export const MOTION_TEST_FINALE_RESOLVE_SWIPE_START_FRAME =
  MOTION_TEST_FINALE_CORNER_LINE_PHASE2_START_FRAME;
export const MOTION_TEST_FINALE_AGENT_BUILDER_RESOLVE_SWIPE_FRAMES = 12;
export const MOTION_TEST_FINALE_PRODUCT_TITLE_SCALE_UP_FRAMES = 28;
export const MOTION_TEST_FINALE_PRODUCT_TITLE_SCALE_DOWN_FRAMES = 18;
export const MOTION_TEST_FINALE_PRODUCT_TITLE_SWITCH_FRAMES = 2;
export const MOTION_TEST_FINALE_PRODUCT_TITLE_SLOT_FRAMES =
  MOTION_TEST_FINALE_PRODUCT_TITLE_SCALE_UP_FRAMES +
  MOTION_TEST_FINALE_PRODUCT_TITLE_SCALE_DOWN_FRAMES +
  MOTION_TEST_FINALE_PRODUCT_TITLE_SWITCH_FRAMES;
export const MOTION_TEST_FINALE_PRODUCT_TITLE_CROSSFADE_FRAMES = 16;
export const MOTION_TEST_FINALE_AGENT_BUILDER_SCALE_START = 0.86;
/** @deprecated Use MOTION_TEST_FINALE_AGENT_BUILDER_SCALE_START */
export const MOTION_TEST_FINALE_PRODUCT_TITLE_SCALE_START =
  MOTION_TEST_FINALE_AGENT_BUILDER_SCALE_START;
/** @deprecated Per-title slot timing */
export const MOTION_TEST_FINALE_AGENT_BUILDER_CROSSFADE_FRAMES =
  MOTION_TEST_FINALE_PRODUCT_TITLE_CROSSFADE_FRAMES;
/** @deprecated Per-title slot timing */
export const MOTION_TEST_FINALE_AGENT_BUILDER_SCALE_FRAMES =
  MOTION_TEST_FINALE_PRODUCT_TITLE_SCALE_UP_FRAMES;
export const MOTION_TEST_FINALE_AGENT_BUILDER_FONT_SIZE = motionTestPx(152);
/** Longest product title — scaled down so it matches the visual weight of the others. */
export const MOTION_TEST_FINALE_SMART_APPOINTMENTS_FONT_SCALE = 0.84;
export const MOTION_TEST_FINALE_SMART_APPOINTMENTS_INDEX =
  MOTION_TEST_FINALE_PRODUCT_TITLES.indexOf("Smart Appointments");
export const MOTION_TEST_FINALE_PRODUCT_TITLE_SEQUENCE_FRAMES =
  MOTION_TEST_FINALE_PRODUCT_TITLES.length *
  MOTION_TEST_FINALE_PRODUCT_TITLE_SLOT_FRAMES;
export const MOTION_TEST_FINALE_AGENT_BUILDER_END_HOLD_FRAMES = 0;
export const MOTION_TEST_FINALE_AGENT_BUILDER_END_FRAME = Math.max(
  MOTION_TEST_FINALE_RESOLVE_SWIPE_START_FRAME +
    MOTION_TEST_FINALE_AGENT_BUILDER_RESOLVE_SWIPE_FRAMES,
  MOTION_TEST_FINALE_AGENT_BUILDER_START_FRAME +
    MOTION_TEST_FINALE_PRODUCT_TITLE_SEQUENCE_FRAMES,
);
/** Camera punch-in — overlaps Auto Prior Auth before its scale pulse finishes. */
export const MOTION_TEST_FINALE_AUTO_PRIOR_AUTH_INDEX =
  MOTION_TEST_FINALE_PRODUCT_TITLES.length - 1;
export const MOTION_TEST_FINALE_CAMERA_JUMP_START_FRAME =
  MOTION_TEST_FINALE_AGENT_BUILDER_START_FRAME +
  MOTION_TEST_FINALE_AUTO_PRIOR_AUTH_INDEX *
    MOTION_TEST_FINALE_PRODUCT_TITLE_SLOT_FRAMES +
  Math.floor(MOTION_TEST_FINALE_PRODUCT_TITLE_SCALE_UP_FRAMES * 0.6);
/** Scale until corner strokes clear the viewport (top-right origin). */
export const MOTION_TEST_FINALE_CAMERA_JUMP_SCALE =
  MOTION_TEST_WIDTH / MOTION_TEST_FINALE_CORNER_LINE_EDGE_INSET_PX + 0.35;
export const MOTION_TEST_FINALE_CAMERA_JUMP_FRAMES = 32;
export const MOTION_TEST_FINALE_CAMERA_JUMP_ORIGIN_X_RATIO = 1;
export const MOTION_TEST_FINALE_CAMERA_JUMP_ORIGIN_Y_RATIO = 0;
export const MOTION_TEST_FINALE_CAMERA_JUMP_HOLD_FRAMES = 6;
export const MOTION_TEST_FINALE_CAMERA_JUMP_END_FRAME =
  MOTION_TEST_FINALE_CAMERA_JUMP_START_FRAME +
  MOTION_TEST_FINALE_CAMERA_JUMP_FRAMES;
export const MOTION_TEST_FINALE_LAUNCH_CARD_START_FRAME =
  MOTION_TEST_FINALE_CAMERA_JUMP_END_FRAME +
  MOTION_TEST_FINALE_CAMERA_JUMP_HOLD_FRAMES;
export const MOTION_TEST_FINALE_LAUNCH_CARD_LINE1 = "Launching Fall 2026";
export const MOTION_TEST_FINALE_LAUNCH_CARD_LINE2 = "doe.care";
export const MOTION_TEST_FINALE_LAUNCH_CARD_FADE_FRAMES = 14;
export const MOTION_TEST_FINALE_LAUNCH_CARD_LINE1_SCALE_START =
  MOTION_TEST_FINALE_AGENT_BUILDER_SCALE_START;
export const MOTION_TEST_FINALE_LAUNCH_CARD_LINE1_SCALE_UP_FRAMES =
  MOTION_TEST_FINALE_PRODUCT_TITLE_SCALE_UP_FRAMES;
export const MOTION_TEST_FINALE_LAUNCH_CARD_LINE1_SCALE_DOWN_FRAMES =
  MOTION_TEST_FINALE_PRODUCT_TITLE_SCALE_DOWN_FRAMES;
export const MOTION_TEST_FINALE_LAUNCH_CARD_LINE1_PULSE_FRAMES =
  MOTION_TEST_FINALE_LAUNCH_CARD_LINE1_SCALE_UP_FRAMES +
  MOTION_TEST_FINALE_LAUNCH_CARD_LINE1_SCALE_DOWN_FRAMES;
export const MOTION_TEST_FINALE_LAUNCH_CARD_LINE1_POST_PULSE_HOLD_FRAMES = 0;
/** Visible through full pulse — scale starts at frame 0 while opacity fades in. */
export const MOTION_TEST_FINALE_LAUNCH_CARD_LINE1_VISIBLE_FRAMES =
  MOTION_TEST_FINALE_LAUNCH_CARD_LINE1_PULSE_FRAMES;
/** @deprecated Use MOTION_TEST_FINALE_LAUNCH_CARD_LINE1_VISIBLE_FRAMES */
export const MOTION_TEST_FINALE_LAUNCH_CARD_LINE1_HOLD_FRAMES = Math.max(
  0,
  MOTION_TEST_FINALE_LAUNCH_CARD_LINE1_VISIBLE_FRAMES -
    MOTION_TEST_FINALE_LAUNCH_CARD_FADE_FRAMES,
);
/** @deprecated Use MOTION_TEST_FINALE_LAUNCH_CARD_LINE1_SCALE_UP/DOWN_FRAMES */
export const MOTION_TEST_FINALE_LAUNCH_CARD_LINE1_SCALE_FRAMES =
  MOTION_TEST_FINALE_LAUNCH_CARD_FADE_FRAMES +
  MOTION_TEST_FINALE_LAUNCH_CARD_LINE1_HOLD_FRAMES;
export const MOTION_TEST_FINALE_LAUNCH_CARD_SWITCH_FRAMES = 4;
export const MOTION_TEST_FINALE_LAUNCH_CARD_LINE2_SCALE_START =
  MOTION_TEST_FINALE_AGENT_BUILDER_SCALE_START;
/** @deprecated Use MOTION_TEST_FINALE_LAUNCH_CARD_LINE2_SCALE_UP_FRAMES */
export const MOTION_TEST_FINALE_LAUNCH_CARD_LINE2_SCALE_UP_FRAMES_LEGACY =
  MOTION_TEST_FINALE_PRODUCT_TITLE_SCALE_UP_FRAMES;
/** @deprecated Line2 uses one slow scale-up through the final slash, not a pulse */
export const MOTION_TEST_FINALE_LAUNCH_CARD_LINE2_SCALE_DOWN_FRAMES =
  MOTION_TEST_FINALE_PRODUCT_TITLE_SCALE_DOWN_FRAMES;
/** @deprecated Line2 uses one slow scale-up through the final slash, not a pulse */
export const MOTION_TEST_FINALE_LAUNCH_CARD_LINE2_PULSE_FRAMES =
  MOTION_TEST_FINALE_PRODUCT_TITLE_SCALE_UP_FRAMES +
  MOTION_TEST_FINALE_PRODUCT_TITLE_SCALE_DOWN_FRAMES;
/** Scale doe.care + slashes rest at after the slow scale-up completes. */
export const MOTION_TEST_FINALE_LAUNCH_CARD_LINE2_REST_SCALE = 1;
/** End scale on the last launch-card frame — keeps motion visible through pitchdeck hold. */
export const MOTION_TEST_FINALE_LAUNCH_CARD_LINE2_SCALE_END = 1.12;
export const MOTION_TEST_FINALE_LAUNCH_CARD_LINE2_MOTIONLESS_HOLD_FRAMES = 8;
export const MOTION_TEST_FINALE_LAUNCH_CARD_SLASH = "/";
export const MOTION_TEST_FINALE_LAUNCH_CARD_SLASH_REVEAL_FRAMES = 6;
export const MOTION_TEST_FINALE_LAUNCH_CARD_LINE2_ALONE_FRAMES =
  MOTION_TEST_FINALE_LAUNCH_CARD_LINE2_MOTIONLESS_HOLD_FRAMES +
  MOTION_TEST_FINALE_LAUNCH_CARD_SLASH_REVEAL_FRAMES;
/** @deprecated Use MOTION_TEST_FINALE_LAUNCH_CARD_LINE2_ALONE_FRAMES */
export const MOTION_TEST_FINALE_LAUNCH_CARD_LINE2_ALONE_HOLD_FRAMES =
  MOTION_TEST_FINALE_LAUNCH_CARD_LINE2_ALONE_FRAMES;
/** @deprecated Use MOTION_TEST_FINALE_LAUNCH_CARD_LINE2_ALONE_HOLD_FRAMES */
export const MOTION_TEST_FINALE_LAUNCH_CARD_LINE2_HOLD_FRAMES =
  MOTION_TEST_FINALE_LAUNCH_CARD_LINE2_ALONE_HOLD_FRAMES;
export const MOTION_TEST_FINALE_LAUNCH_CARD_PATH_WORDS = [
  "waitlist",
  "hiring",
  "pitchdeck",
] as const;
export const MOTION_TEST_FINALE_LAUNCH_CARD_PATHS =
  MOTION_TEST_FINALE_LAUNCH_CARD_PATH_WORDS.map(
    (word) => `${MOTION_TEST_FINALE_LAUNCH_CARD_SLASH}${word}`,
  );
export const MOTION_TEST_FINALE_LAUNCH_CARD_PATH_TYPE_FRAMES_PER_CHAR = 3;
export const MOTION_TEST_FINALE_LAUNCH_CARD_PATH_DELETE_FRAMES_PER_CHAR = 2;
export const MOTION_TEST_FINALE_LAUNCH_CARD_PATH_HOLD_FRAMES = 32;
/** Hold on the last path after typing completes, then cut to the final Doe outro. */
export const MOTION_TEST_FINALE_LAUNCH_CARD_PATH_FINAL_POST_TYPE_HOLD_FRAMES =
  Math.round(1 * MOTION_TEST_DESIGN_FPS);
/** @deprecated Use MOTION_TEST_FINALE_LAUNCH_CARD_PATH_FINAL_POST_TYPE_HOLD_FRAMES */
export const MOTION_TEST_FINALE_LAUNCH_CARD_PATH_FINAL_HOLD_FRAMES =
  MOTION_TEST_FINALE_LAUNCH_CARD_PATH_FINAL_POST_TYPE_HOLD_FRAMES;

/** @deprecated Use MOTION_TEST_FINALE_LAUNCH_CARD_PATHS[0] */
export const MOTION_TEST_FINALE_LAUNCH_CARD_WAITLIST_PATH =
  MOTION_TEST_FINALE_LAUNCH_CARD_PATHS[0];
/** @deprecated Use path sequence timing */
export const MOTION_TEST_FINALE_LAUNCH_CARD_WAITLIST_TYPE_FRAMES =
  MOTION_TEST_FINALE_LAUNCH_CARD_PATHS[0].length *
  MOTION_TEST_FINALE_LAUNCH_CARD_PATH_TYPE_FRAMES_PER_CHAR;
/** @deprecated Use MOTION_TEST_FINALE_LAUNCH_CARD_PATH_FINAL_POST_TYPE_HOLD_FRAMES */
export const MOTION_TEST_FINALE_LAUNCH_CARD_WAITLIST_HOLD_FRAMES =
  MOTION_TEST_FINALE_LAUNCH_CARD_PATH_FINAL_POST_TYPE_HOLD_FRAMES;

export function getMotionTestFinaleLaunchCardPathTypeFrames(path: string): number {
  return path.length * MOTION_TEST_FINALE_LAUNCH_CARD_PATH_TYPE_FRAMES_PER_CHAR;
}

export function getMotionTestFinaleLaunchCardPathDeleteFrames(path: string): number {
  return path.length * MOTION_TEST_FINALE_LAUNCH_CARD_PATH_DELETE_FRAMES_PER_CHAR;
}

export const MOTION_TEST_FINALE_LAUNCH_CARD_PATH_SEQUENCE_FRAMES = (() => {
  let total = 0;

  for (let index = 0; index < MOTION_TEST_FINALE_LAUNCH_CARD_PATH_WORDS.length; index++) {
    const word = MOTION_TEST_FINALE_LAUNCH_CARD_PATH_WORDS[index];
    const isLast = index === MOTION_TEST_FINALE_LAUNCH_CARD_PATH_WORDS.length - 1;

    total += getMotionTestFinaleLaunchCardPathTypeFrames(word);

    if (isLast) {
      total += MOTION_TEST_FINALE_LAUNCH_CARD_PATH_FINAL_POST_TYPE_HOLD_FRAMES;
    } else {
      total += MOTION_TEST_FINALE_LAUNCH_CARD_PATH_HOLD_FRAMES;
      total += getMotionTestFinaleLaunchCardPathDeleteFrames(word);
    }
  }

  return total;
})();

/** Slow scale-up runs from doe.care through the cut to the final Doe outro. */
export function getMotionTestFinaleLaunchCardLine2ScaleUpFrames(): number {
  return (
    MOTION_TEST_FINALE_LAUNCH_CARD_SWITCH_FRAMES +
    MOTION_TEST_FINALE_LAUNCH_CARD_LINE2_ALONE_FRAMES +
    MOTION_TEST_FINALE_LAUNCH_CARD_PATH_SEQUENCE_FRAMES
  );
}

export const MOTION_TEST_FINALE_LAUNCH_CARD_LINE2_SCALE_UP_FRAMES =
  getMotionTestFinaleLaunchCardLine2ScaleUpFrames();

export const MOTION_TEST_FINALE_LAUNCH_CARD_LINE1_FONT_SIZE = motionTestPx(96);
export const MOTION_TEST_FINALE_LAUNCH_CARD_LINE2_FONT_SIZE = motionTestPx(132);
export const MOTION_TEST_FINALE_LAUNCH_CARD_PATH_FONT_SIZE = motionTestPx(132);
/** Bar width as a fraction of path font size — matches SF Pro Display stroke weight. */
export const MOTION_TEST_FINALE_LAUNCH_CARD_PATH_CURSOR_WIDTH_EM = 0.072;
export const MOTION_TEST_FINALE_LAUNCH_CARD_PATH_CURSOR_HEIGHT_EM = 0.92;
/** @deprecated Use MOTION_TEST_FINALE_LAUNCH_CARD_PATH_FONT_SIZE */
export const MOTION_TEST_FINALE_LAUNCH_CARD_WAITLIST_FONT_SIZE =
  MOTION_TEST_FINALE_LAUNCH_CARD_PATH_FONT_SIZE;
export const MOTION_TEST_FINALE_LAUNCH_CARD_SEQUENCE_FRAMES =
  MOTION_TEST_FINALE_LAUNCH_CARD_LINE1_VISIBLE_FRAMES +
  MOTION_TEST_FINALE_LAUNCH_CARD_SWITCH_FRAMES +
  MOTION_TEST_FINALE_LAUNCH_CARD_LINE2_ALONE_FRAMES +
  MOTION_TEST_FINALE_LAUNCH_CARD_PATH_SEQUENCE_FRAMES;
export const MOTION_TEST_FINALE_LAUNCH_CARD_END_FRAME =
  MOTION_TEST_FINALE_LAUNCH_CARD_START_FRAME +
  MOTION_TEST_FINALE_LAUNCH_CARD_SEQUENCE_FRAMES;
export const MOTION_TEST_FINALE_OUTRO_START_FRAME =
  MOTION_TEST_FINALE_LAUNCH_CARD_END_FRAME;
/** Scale begins during the pitchdeck hold — timeline is unified in finale-doe-lockup-scale-motion. */
/** @deprecated Use getMotionTestFinaleDoeLockupScale timeline */
export const MOTION_TEST_FINALE_OUTRO_SCALE_MOTION_START_FRAME =
  MOTION_TEST_FINALE_OUTRO_START_FRAME -
  MOTION_TEST_FINALE_LAUNCH_CARD_PATH_FINAL_POST_TYPE_HOLD_FRAMES;
export const MOTION_TEST_FINALE_OUTRO_SCALE_START = 0.88;
export const MOTION_TEST_FINALE_OUTRO_SCALE_END = 1.14;
/** @deprecated Scale runs the full outro — kept for total duration only */
export const MOTION_TEST_FINALE_OUTRO_PRE_SCALE_FRAMES = 44;
export const MOTION_TEST_FINALE_OUTRO_HOLD_FRAMES = Math.max(
  1,
  Math.round(MOTION_TEST_DURATION_SEC * MOTION_TEST_DESIGN_FPS) -
    MOTION_TEST_FINALE_OUTRO_START_FRAME -
    MOTION_TEST_FINALE_OUTRO_PRE_SCALE_FRAMES,
);
export const MOTION_TEST_FINALE_OUTRO_FRAMES =
  MOTION_TEST_FINALE_OUTRO_PRE_SCALE_FRAMES + MOTION_TEST_FINALE_OUTRO_HOLD_FRAMES;
export const MOTION_TEST_FINALE_OUTRO_SCALE_UP_FRAMES = MOTION_TEST_FINALE_OUTRO_FRAMES;
export const MOTION_TEST_FINALE_OUTRO_ENTER_FRAMES =
  MOTION_TEST_FINALE_OUTRO_SCALE_UP_FRAMES;
/** @deprecated Lines hold through Agent Builder reveal */
export const MOTION_TEST_FINALE_VERTICAL_LINE_END_HOLD_FRAMES = 0;
export const MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_HOLD_AFTER_ZOOM_FRAMES = Math.max(
  0,
  MOTION_TEST_FINALE_AUDIENCE_CAROUSEL_START_FRAME -
    (MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_ZOOM_START_FRAME +
      MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_ZOOM_FRAMES),
);
/** Diameter fits frame height when scaled from full width. */
export const MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_ZOOM_END_SCALE =
  MOTION_TEST_HEIGHT / Math.max(MOTION_TEST_WIDTH, MOTION_TEST_HEIGHT);
/** Min text scale at zoom end — computed to fit phrase in circle; this is the floor. */
export const MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_TEXT_ZOOM_END_SCALE = 0.42;
/** Inset from circle right edge so “for” stays on gradient at zoom end. */
export const MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_TEXT_CIRCLE_INSET_PX = motionTestPx(56);
/** Approximate char width × letter-spacing for layout without measure. */
export const MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_TEXT_CHAR_WIDTH_RATIO = 0.46;

export const MOTION_TEST_FINALE_INTELLIGENCE_STACK_START_FRAME =
  MOTION_TEST_FINALE_INTELLIGENCE_ISOLATE_START_FRAME +
  MOTION_TEST_FINALE_INTELLIGENCE_ISOLATE_HOLD_FRAMES;

export const MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_START_FRAME =
  MOTION_TEST_FINALE_INTELLIGENCE_STACK_START_FRAME +
  MOTION_TEST_FINALE_INTELLIGENCE_STACK_FRAMES;

export const MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_HOLD_BEFORE_ZOOM_FRAMES =
  MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_ZOOM_START_FRAME -
  MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_START_FRAME;

/** Stack drift + pan run through hold and the first half of scale-down. */
export const MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_STACK_MOTION_FRAMES =
  MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_HOLD_BEFORE_ZOOM_FRAMES +
  Math.floor(MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_ZOOM_FRAMES / 2);
/** Keep drifting upward through scale-down + audience carousel. */
export const MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_STACK_MOTION_END_FRAME =
  MOTION_TEST_FINALE_GRADIENT_RESOLVE_START_FRAME;
export const MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_STACK_PAN_CONTINUATION_PX = motionTestPx(52);
export const MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_STACK_DRIFT_CONTINUATION_SCALE = 0.42;

export const MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_HOLD_FRAMES =
  MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_HOLD_BEFORE_ZOOM_FRAMES +
  MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_ZOOM_FRAMES +
  MOTION_TEST_FINALE_INTELLIGENCE_FLIPPED_HOLD_AFTER_ZOOM_FRAMES;

export const MOTION_TEST_FINALE_END_DESIGN_FRAME = Math.round(
  MOTION_TEST_DURATION_SEC * MOTION_TEST_DESIGN_FPS,
);
export const MOTION_TEST_FINALE_END_FRAME = Math.round(
  MOTION_TEST_DURATION_SEC * MOTION_TEST_FPS,
);

/** @deprecated Use MOTION_TEST_FINALE_INTELLIGENCE_ISOLATE_HOLD_FRAMES */
export const MOTION_TEST_FINALE_INTELLIGENCE_BORDER_HOLD_FRAMES =
  MOTION_TEST_FINALE_INTELLIGENCE_ISOLATE_HOLD_FRAMES;

/** @deprecated Finale follows opposite-color flash directly */
export const MOTION_TEST_VERY_BIG_DOE_START_FRAME = MOTION_TEST_FINALE_TYPE_START_FRAME;

export const MOTION_TEST_TEXT_SEQUENCE_END_FRAME = MOTION_TEST_FINALE_END_FRAME;

/** Gradient pull completes as big Doe cuts in. */
export const MOTION_TEST_GRADIENT_PULL_FRAMES = MOTION_TEST_DOE_JUMP_FRAME;

export const MOTION_TEST_WHITE_HOLD_SEC = 1;
export const MOTION_TEST_WHITE_HOLD_FRAMES =
  MOTION_TEST_DESIGN_FPS * MOTION_TEST_WHITE_HOLD_SEC;

export const MOTION_TEST_TITLE_FRAMES = MOTION_TEST_FINALE_END_FRAME;
export const MOTION_TEST_DURATION_FRAMES = MOTION_TEST_TITLE_FRAMES;

/** Background bed — Jane & The Boy “Waste Our Time”. */
export const MOTION_TEST_BG_MUSIC_SRC = "motion/waste-our-time.mp3";
export const MOTION_TEST_BG_MUSIC_GAIN = 0.85;
export const MOTION_TEST_BG_MUSIC_START_SEC = 60 + 22;
export const MOTION_TEST_BG_MUSIC_START_FRAMES =
  MOTION_TEST_FPS * MOTION_TEST_BG_MUSIC_START_SEC;
export const MOTION_TEST_BG_MUSIC_END_FRAMES =
  MOTION_TEST_BG_MUSIC_START_FRAMES + MOTION_TEST_DURATION_FRAMES;
export const MOTION_TEST_PULL_FRAMES = MOTION_TEST_GRADIENT_PULL_FRAMES;
export const MOTION_TEST_PULL_SEC =
  MOTION_TEST_GRADIENT_PULL_FRAMES / MOTION_TEST_DESIGN_FPS;

/** Opening pull + all brown-scene beds — motion4 brown stack. */
export const MOTION_TEST_OPENING_FRAME_GRADIENT = MOTION_TEST_BROWN_BG_GRADIENT;

/** Stack column text — brown gradient clipped inside each Doe line. */
export const MOTION_TEST_DOE_STACK_FLOW_GRADIENT = MOTION_TEST_BROWN_TEXT_GRADIENT;

/** Reversed stack hold — brown gradient bed behind gold Doe column. */
export const MOTION_TEST_DOE_STACK_REVERSED_BACKGROUND_GRADIENT = MOTION_TEST_BROWN_BG_GRADIENT;

/** Full-frame brown bed — white/gold text phases. */
export const MOTION_TEST_TITLE_GRADIENT = MOTION_TEST_BROWN_BG_GRADIENT;

export const MOTION_TEST_GRADIENT_TEXT_GRADIENT = MOTION_TEST_BROWN_TEXT_GRADIENT;

/** Vertical stroke — brown gradient, top → bottom (motion4 gold direction). */
export const MOTION_TEST_GRADIENT_LINE_STROKE_GRADIENT = MOTION_TEST_BROWN_TEXT_GRADIENT;

/** Horizontal stroke — brown gradient, left → right. */
export const MOTION_TEST_GRADIENT_LINE_STROKE_GRADIENT_HORIZONTAL =
  MOTION_TEST_BROWN_LINE_STROKE_GRADIENT_HORIZONTAL;

export const MOTION_TEST_GRADIENT_LAYER_HEIGHT_RATIO = 2.75;
export const MOTION_TEST_PULL_START_Y_RATIO = -0.24;
export const MOTION_TEST_PULL_END_Y_RATIO = -0.05;

export const MOTION_TEST_WHITE_OVERLAY_FADE_FRAMES = 1;
export const MOTION_TEST_VERY_BIG_DOE_WHITE_IN_FRAMES = 2;

export const MOTION_TEST_TITLE_FONT_SIZE = motionTestPx(128);
export const MOTION_TEST_TEXT_SCALE_START = 1.08;
export const MOTION_TEST_TEXT_SCALE_END = 1;
export const MOTION_TEST_DOE_SCALE_DELTA =
  MOTION_TEST_TEXT_SCALE_START - MOTION_TEST_TEXT_SCALE_END;
export const MOTION_TEST_DOE_JUMP_FONT_SIZE = motionTestPx(156);
export const MOTION_TEST_DOE_JUMP_SCALE = 1.22;
export const MOTION_TEST_FRONT_DESK_FAST_SCALE_END = 0.88;

export const MOTION_TEST_DOE_STACK_RADIUS = motionTestPx(4);
export const MOTION_TEST_DOE_STACK_LINE_HEIGHT = 0.92;
export const MOTION_TEST_DOE_STACK_OPACITY_FALLOFF = 0.22;
export const MOTION_TEST_DOE_STACK_MIN_OPACITY = 0.07;

/** Very big white Doe flash — Lora on white. */
export const MOTION_TEST_VERY_BIG_DOE_FONT_SIZE = Math.round(MOTION_TEST_HEIGHT * 0.62);
export const MOTION_TEST_VERY_BIG_DOE_LINE_HEIGHT = 0.92;
export const MOTION_TEST_FINALE_OUTRO_DOE_FONT_SIZE = Math.round(MOTION_TEST_HEIGHT * 0.19);
export const MOTION_TEST_FINALE_OUTRO_DOE_LINE_HEIGHT = 1;
export const MOTION_TEST_VERY_BIG_DOE_ON_WHITE_COLOR = MOTION_TEST_BROWN_MID;

/** Finale — solid brown accent on gold panels. */
export const MOTION_TEST_FINALE_TYPE_COLOR = MOTION_TEST_BROWN_MID;
/** Gold text on brown gradient scenes — use getMotionTestGoldTextStyle() for clipped type. */
export const MOTION_TEST_FINALE_INVERTED_TEXT_COLOR = MOTION_TEST_GOLD_MID;
export const MOTION_TEST_FINALE_INTELLIGENCE_BORDER_COLOR = "rgba(0, 0, 0, 0.14)";
export const MOTION_TEST_FINALE_TYPE_FONT_SIZE = motionTestPx(340);
/** Scaled so full phrase fits dead center — proportional to building beat width. */
export const MOTION_TEST_FINALE_FULL_PHRASE_FONT_SIZE = Math.round(
  (MOTION_TEST_FINALE_TYPE_FONT_SIZE * MOTION_TEST_FINALE_BUILDING_WORD.length) /
    MOTION_TEST_FINALE_FULL_PHRASE_WORD.length,
);
export const MOTION_TEST_FINALE_TYPE_LINE_HEIGHT = 0.94;
/** Tighter leading for the two-line full phrase stack. */
export const MOTION_TEST_FINALE_TWO_LINE_LEADING = 0.82;
export const MOTION_TEST_FINALE_CURSOR_BLINK_FRAMES = 16;
