export {
  PROTO_GRAIN_BG as HERO_CAROUSEL_GRAIN_BG,
  PROTO_GRAIN_SIZE as HERO_CAROUSEL_GRAIN_SIZE,
  PROTO_GRAIN_OPACITY as HERO_CAROUSEL_GRAIN_OPACITY,
  PROTO_HERO_GRAIN_OPACITY as HERO_CAROUSEL_HERO_GRAIN_OPACITY,
} from "@/lib/proto/proto-phone-grain";
